#!/bin/bash

# TODO: need to make sure Redis server is started?

start_server=false
start_browser=false

while getopts ":sbk" opt; do
  case $opt in
    s)
      start_server=true
      ;;
    b)
      start_browser=true
      ;;
    k)
      sudo pkill -9 bot50.js
      exit
      ;;
    \?)
      echo "Invalid option: -$OPTARG" >&2
      exit 1
      ;;
  esac
done

if [[ ! ($start_server = true || $start_browser = true) ]]; then
    start_server=true
    start_browser=true
fi

if [[ $start_server = true ]]; then
    (pgrep bot50.js > /dev/null) && echo "Server is already running!" || ((cd /opt/bot50 && ./bot50.js &>> /opt/bot50/bot50.log &) && echo "Server started!")
fi

if [[ $start_browser = true ]]; then
    google-chrome http://localhost:3000
fi

